---
title: "10.3 Final Project Step 2"
author: "Amelia Farrell"
date: "November 1st 2021"
output:
  pdf_document: default
  word_document: default
---

# Supermarket Shrink 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = "C:/Users/Amelia/Documents/Bellevue/dsc520/completed/Final-Project")
Food_Loss <- read.csv("Food_Loss_and_Waste.csv")

library(ggplot2)
library(GGally)
library(ppcor)
library(purrr)
library(car)
```

## Importing and cleaning the data
As described in Project Step 2, we will be using three different data sets to answer our problem statement (aka Business Case).I will review how we pulled and cleaned each data set in preparation for our final set. 

1. *Food Loss and Waste Database*
Purpose of data set - this data set will give us insight to the top fruits and vegetables with the highest % loss at the grocery store (Retail level of the value chain).

This data base contains much more information than we need for this analysis. Therefore, we will be downloading data based off the following pentameters;

 * Year Range - 2000 through 2017 (data set ends in 2017 and we need to go back to year 2000 in order to have enough data to work with for the averge loss per item).
 * Aggregation - Country
 * Country - United States
 * Basket Items - Fruit & Vegetables
 * Value Chain - Retail
 * Commodity - All
 * Method of Data Collection - All
  
After downloading the data set with the above perameters from the The Food and Agriculture Organization site, we can see that it has 21 variables. 



## What does the final data set look like?

## Questions for future steps.

## What information is not self-evident?

## What are different ways you could look at this data?

## How do you plan to slice and dice the data?

## How could you summarize your data to answer key questions?
## What types of plots and tables will help you to illustrate the findings to your questions?
## Do you plan on incorporating any machine learning techniques to answer your research questions? Explain.
## Questions for future steps.



## References

wheresmyshrink.com, 2012. Executive Summary. http://wheresmyshrink.com/executivesummary.html?fbclid=IwAR0w7KKjS-4Lr1wJ3JuJ2ZYbsZGZbc57Go4NuBinNwytYNG5911QUBtXXYE.

FAO, 2021. Food Loss and Waste Database. The Food and Agriculture Organization (FAO). https://www.fao.org/platform-food-loss-waste/flw-data/es/.

Dedhia H., 2020. Groceries dataset. Kaggle.com.
https://www.kaggle.com/heeraldedhia/groceries-dataset

Food Marketing Institute & Cornell University, 2020. The Food Keeper. fightbac.org.
https://lee.ces.ncsu.edu/wp-content/uploads/2012/12/TheFoodKeeper.pdf?fwd=no&fbclid=IwAR2QE_yWd_E6kzD7Sp18AnLN36h7uLPpmM7CrsUZC91OQz_pHi_hT3jZvBU