---
title: "10.3 Final Project Step 2"
author: "Amelia Farrell"
date: "November 1st 2021"
output:
  word_document: default
  pdf_document: default
---

# Supermarket Shrink 

## How to import and clean my data

## What does the final data set look like?

## Questions for future steps.

## What information is not self-evident?

## What are different ways you could look at this data?

## How do you plan to slice and dice the data?

## How could you summarize your data to answer key questions?
## What types of plots and tables will help you to illustrate the findings to your questions?
## Do you plan on incorporating any machine learning techniques to answer your research questions? Explain.
## Questions for future steps.



## References

wheresmyshrink.com, 2012. Executive Summary. http://wheresmyshrink.com/executivesummary.html?fbclid=IwAR0w7KKjS-4Lr1wJ3JuJ2ZYbsZGZbc57Go4NuBinNwytYNG5911QUBtXXYE.

FAO, 2021. Food Loss and Waste Database. The Food and Agriculture Organization (FAO). https://www.fao.org/platform-food-loss-waste/flw-data/es/.

Dedhia H., 2020. Groceries dataset. Kaggle.com.
https://www.kaggle.com/heeraldedhia/groceries-dataset

Food Marketing Institute & Cornell University, 2020. The Food Keeper. fightbac.org.
https://lee.ces.ncsu.edu/wp-content/uploads/2012/12/TheFoodKeeper.pdf?fwd=no&fbclid=IwAR2QE_yWd_E6kzD7Sp18AnLN36h7uLPpmM7CrsUZC91OQz_pHi_hT3jZvBU